CREATE TABLE IF NOT EXISTS players (
  id INT AUTO_INCREMENT PRIMARY KEY,
  player VARCHAR(100),
  nation VARCHAR(50),
  pos VARCHAR(10),
  squad VARCHAR(100),
  comp VARCHAR(50),
  age INT,
  born INT,
  mp INT,
  starts INT,
  min INT,
  nineties FLOAT,
  gls INT,
  ast INT,
  g_a INT,
  xg FLOAT,
  xag FLOAT,
  npxg FLOAT,
  g_pk INT,
  tkl INT,
  tklw INT,
  blocks INT,
  interceptions INT,
  tkl_int INT,
  clr INT,
  err INT,
  prgp INT,
  prgc INT,
  kp INT,
  cmp_pct FLOAT,
  ast_passing INT,
  xa FLOAT,
  ppa INT,
  ga INT,
  saves INT,
  save_pct FLOAT,
  cs INT,
  cs_pct FLOAT,
  pka INT,
  pksv INT,
  touches INT,
  carries INT,
  prgr INT,
  mis INT,
  dis INT,
  crdy INT,
  crdr INT,
  pkwon INT,
  pkcon INT,
  recov INT
);

LOAD DATA INFILE '/docker-entrypoint-initdb.d/players.csv'
INTO TABLE players
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(player, nation, pos, squad, comp, age, born, mp, starts, min, nineties,
gls, ast, g_a, xg, xag, npxg, g_pk, tkl, tklw, blocks, interceptions,
tkl_int, clr, err, prgp, prgc, kp, cmp_pct, ast_passing, xa, ppa,
ga, saves, save_pct, cs, cs_pct, pka, pksv, touches, carries, prgr,
mis, dis, crdy, crdr, pkwon, pkcon, recov);

CREATE TABLE IF NOT EXISTS cars (
  id INT AUTO_INCREMENT PRIMARY KEY,
  car_id VARCHAR(20),
  sale_date VARCHAR(20),
  customer_name VARCHAR(100),
  gender VARCHAR(10),
  annual_income INT,
  dealer_name VARCHAR(150),
  company VARCHAR(50),
  model VARCHAR(100),
  engine VARCHAR(100),
  transmission VARCHAR(20),
  color VARCHAR(30),
  price INT,
  dealer_no VARCHAR(20),
  body_style VARCHAR(30),
  phone VARCHAR(20),
  dealer_region VARCHAR(50)
);